name: API CI

#on: [push]
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  linter:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          chache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run linter
        shell: bash
        run: npm run lint
  unit-test:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          chache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run unit tests
        shell: bash
        run: npm run test
  e2e-test:
    runs-on: ubuntu-lastest
    container:
      image: node:14
    services:
      mongo-e2e:
        image: mongo:4.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123
    stpes:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run e2e tests
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://test:test123@mongo-e2e:27017?retryWrites=true&writeConcern=majority
